AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EC2InstanceType:
    Type: String
    Default: t2.micro
    Description: "EC2 Instance Type"

  KeyName:
    Type: String
    Description: "Name of an existing EC2 KeyPair to enable SSH access"

Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Enable SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 
        Ref: InstanceType
      KeyName: 
        Ref: KeyName
      ImageId: ami-0c55b159cbfafe1f0  # Replace with the appropriate AMI ID
      SecurityGroups:
        - 
          Ref: SecurityGroup

Outputs:
  InstancePublicIP:
    Description: "Public IP of the EC2 instance"
    Value: 
      Fn::GetAtt: 
        - EC2Instance
        - PublicIp
